name: Continuous Delivery

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: npm ci
      - name: Build all packages
        run: |
          npm run lerna:bootstrap
          npm run lerna:build
      - name: Publish to NPM
        run: |
          # Tag release
          TAG=$([[ ${{ github.event_name }} == 'push' ]] && echo 'dev')

          # Bump and publish
          npx lerna publish --yes --conventional-prerelease --ignore-scripts --no-verify-access --no-git-tag-version --no-push --pre-dist-tag ${TAG} --preid "${TAG}.$(git rev-parse --verify --short HEAD)" --allow-branch main
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}