name: Node.js Package

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Publish to NPM and Github
        run: |
          # Run Install
          npm ci

          # Identify with GitHub
          git config --global user.email "65198941+knokbak@users.noreply.github.com"
          git config --global user.name "knokbak"

          # Tag release
          TAG=$([[ ${{ github.event_name }} == 'push' ]] && echo 'dev')

          # Bump and publish
          npx lerna version --yes --conventional-commits --conventional-prerelease --ignore-scripts --create-release github --preid "${TAG}.$(git rev-parse --verify --short HEAD)" --allow-branch main
          npx lerna publish --yes --conventional-prerelease --ignore-scripts --no-verify-access --no-git-tag-version --no-push --pre-dist-tag ${TAG} --preid "${TAG}.$(git rev-parse --verify --short HEAD)" --allow-branch main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}